# Generated by Django 2.2.3 on 2019-08-03 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gamer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questions',
            table='questions',
        ),
    ]
