# Generated by Django 2.2.3 on 2019-08-03 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gamer', '0002_auto_20190803_0313'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questions',
            table='problem',
        ),
    ]
