# Generated by Django 2.2.3 on 2019-08-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamer', '0004_auto_20190803_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0, null=True, verbose_name='分数'),
        ),
    ]
