# Generated by Django 2.2.3 on 2019-08-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamer', '0005_auto_20190805_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.CharField(max_length=3, null=True, verbose_name='组别'),
        ),
        migrations.AddField(
            model_name='user',
            name='one',
            field=models.CharField(max_length=1, null=True, verbose_name='选项'),
        ),
        migrations.AddField(
            model_name='user',
            name='three',
            field=models.CharField(max_length=1, null=True, verbose_name='选项'),
        ),
        migrations.AddField(
            model_name='user',
            name='two',
            field=models.CharField(max_length=1, null=True, verbose_name='选项'),
        ),
    ]
