# Generated by Django 2.2.3 on 2019-08-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamer', '0006_auto_20190806_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='five',
            field=models.CharField(default='A', max_length=1, verbose_name='选项'),
        ),
        migrations.AddField(
            model_name='user',
            name='four',
            field=models.CharField(default='A', max_length=1, verbose_name='选项'),
        ),
        migrations.AlterField(
            model_name='user',
            name='one',
            field=models.CharField(default='A', max_length=1, verbose_name='选项'),
        ),
        migrations.AlterField(
            model_name='user',
            name='three',
            field=models.CharField(default='A', max_length=1, verbose_name='选项'),
        ),
        migrations.AlterField(
            model_name='user',
            name='two',
            field=models.CharField(default='A', max_length=1, verbose_name='选项'),
        ),
    ]
