# Generated by Django 2.2.3 on 2019-08-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamer', '0007_auto_20190806_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='five',
            field=models.CharField(max_length=1, null=True, verbose_name='选项'),
        ),
        migrations.AlterField(
            model_name='user',
            name='four',
            field=models.CharField(max_length=1, null=True, verbose_name='选项'),
        ),
        migrations.AlterField(
            model_name='user',
            name='one',
            field=models.CharField(max_length=1, null=True, verbose_name='选项'),
        ),
        migrations.AlterField(
            model_name='user',
            name='three',
            field=models.CharField(max_length=1, null=True, verbose_name='选项'),
        ),
        migrations.AlterField(
            model_name='user',
            name='two',
            field=models.CharField(max_length=1, null=True, verbose_name='选项'),
        ),
    ]
