# Generated by Django 2.2.4 on 2019-08-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gamer', '0008_auto_20190806_1125'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questions',
            table='questions',
        ),
    ]
